# Generated by Django 5.2.10 on 2026-05-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Farmer', 'Commercial Farmer'), ('Home Gardener', 'Home / Terrace Gardener'), ('Nursery', 'Nursery Operator'), ('Distributor', 'Fertilizer Distributor')], max_length=30)),
                ('product', models.CharField(choices=[('Goat Manure', 'Goat Manure'), ('Cow Manure', 'Cow Manure'), ('Multiple', 'Multiple Products')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active Inquiry'), ('Completed', 'Delivery Completed')], default='Active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
