# Generated by Django 5.2.14 on 2026-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='product',
            field=models.CharField(choices=[('Goat Manure', 'Goat Manure'), ('Cow Manure', 'Cow Manure'), ('Straw Bales', 'Straw Bales'), ('Multiple', 'Multiple Products')], max_length=50),
        ),
    ]
